# Generated by Django 3.0.4 on 2020-03-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rangoapp', '0002_views_likes_in_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
